apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixy
  namespace: kafka
  labels:
    app: pixy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pixy
  template:
    metadata:
      labels:
        app: pixy
    spec:
      containers:
      - name: pixy
        image: mailgun/kafka-pixy:0.17.0@sha256:0b5f4795c0b0d80729fa7415ec70ae4d411e152c6149656dddf01b18184792e0
        ports:
        - containerPort: 80
        command:
        - kafka-pixy
        - -kafkaPeers
        - bootstrap.kafka:9092
        - -zookeeperPeers
        - zookeeper.kafka:2181
        - -tcpAddr
        - 0.0.0.0:80
