apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: prevoir-dev-rabbitmq-pdb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prevoir-dev-rabbitmq
