bases:
# This kustomization needs to depend on one with kafka in it, to add the sidecar,
# but it needs to be the kafka from the chosen variant, as ../kafka here would override other kustomizations
#- ../kafka
#- ../variants/scale-1
resources:
- 10-metrics-config.yml
patchesStrategicMerge:
- 50-kafka-jmx-exporter-patch.yml
