apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@bitbucket.org:prevoirsolutionsinformatiques/gitops-baremetal.git
    targetRevision: HEAD
    path: manifests/persistence/consul
    helm:
      valueFiles: 
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: data-consul
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true