# Source: prometheus-mongodb-exporter/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-metrics
  namespace: data-mongodb
  labels:
    app.kubernetes.io/name: prometheus-mongodb-exporter
    app.kubernetes.io/instance: mongodb-metrics
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: prometheus-mongodb-exporter-2.8.1
    app: mongodb-service
type: Opaque
data:
  mongodb-uri : bW9uZ29kYjovL21vbmdvZGItZXhwb3J0ZXI6cGFzc3dvcmRAbW9uZ29kYi0wLm1vbmdvZGItaGVhZGxlc3MuZGF0YS1tb25nb2RiOjI3MDE3LG1vbmdvZGItMS5tb25nb2RiLWhlYWRsZXNzLmRhdGEtbW9uZ29kYjoyNzAxNyxtb25nb2RiLTIubW9uZ29kYi1oZWFkbGVzcy5kYXRhLW1vbmdvZGI6MjcwMTcvYWRtaW4K