apiVersion: v2
name: kube-state-metrics
description: Install kube-state-metrics to generate and expose cluster-level metrics
keywords:
- metric
- monitoring
- prometheus
- kubernetes
type: application
version: 3.4.2
appVersion: 2.1.1
home: https://github.com/naydoo/kube-state-metrics
sources:
- https://github.com/naydoo/kube-state-metrics/
maintainers:
- name: tariq1890
  email: tariq.ibrahim@mulesoft.com
- name: mrueg
  email: manuel@rueg.eu
