apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: loki-grafanadatasource
spec:
  name: loki.yaml
  datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.logging:3100
      isDefault: false
      editable: true
      jsonData:
        maxLines: 1000
