apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.connectionRegistry.name }}-backend
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.connectionRegistry.name }}-backend
  ports:
    - protocol: TCP
      port: {{ .Values.global.backendServicePort }}
      targetPort: http
      name: http
