apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.connectionRegistry.name }}-frontend
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.connectionRegistry.name }}-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.global.frontendServicePort }}
      targetPort: http
      name: http
