apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certmanager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@bitbucket.org:prevoirsolutionsinformatiques/gitops-baremetal.git
    targetRevision: HEAD
    path: manifests/core/cert-manager    
  destination:
    server: https://kubernetes.default.svc
    # namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
