apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: loki-bucket
spec:
  bucketName: loki-chunks-bkt
  storageClassName: rook-ceph-bucket
  additionalConfig:
    maxObjects: "10000000"
    maxSize: "100G"
