apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-metrics-minion
  namespace: monitoring
  labels:
    k8s-app: kafka-metrics-minion
spec:
  namespaceSelector:
    matchNames:
    - kafka
  selector:
    matchLabels:
      app: kafka-minion
      type: openmetrics
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    scrapeTimeout: 30s
    port: http
    scheme: http
    path: /metrics
