apiVersion: v1
kind: Service
metadata:
  name: calico-felix-metrics
  namespace: kube-system
  labels:
    monitoring: calico-felix
    app.kubernetes.io/instance: calico
    k8s-app: calico-node
spec:
  clusterIP: None
  ports:
  - port: 9091
    protocol: TCP 
    name: metrics  
  selector:
    k8s-app: calico-node