bases:
- ../../native
patchesStrategicMerge:
- zoo-9.yaml
- kafka-6.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: kafka
  path: kafka-zookeeper-connect-only-zoo.json
# The nonroot image is distroless and doesn't support a shell that the prestop hook needs
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: zoo
  path: lifecycle-remove.json
# The nonroot image is distroless and has neither shell nor the nc command
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: zoo
  path: zoo-readiness-without-shell.yaml
