apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rabbitmq-system
images:
- name: rabbitmqoperator/cluster-operator-dev
  newName: rabbitmqoperator/cluster-operator
  newTag: latest
resources:
- cluster-operator.yml
- ./prevoir-dev-rabbitmq/