name: frontend-container
apiVersion: v2
version: 0.0.1
appVersion: 0.0.1
description: Frontend-Container
keywords:
  - services
  - frontend-container
maintainers:
  - name: Prevoir Solutions Informatiques
