{{- if or (and .Values.bucket.key .Values.bucket.secret) .Values.bucket.json .Values.bucket.s3ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pg-database.fullname" . }}-backrest-repo-config
  annotations:
    "helm.sh/hook": pre-install
  labels:
{{ include "pg-database.labels" . | indent 4 }}
type: Opaque
data:
{{- if .Values.bucket.s3ca }}
  aws-s3-ca.crt: {{ .Values.bucket.s3ca | b64enc }}
{{- end }}
{{- if and .Values.bucket.key .Values.bucket.secret  }}
  aws-s3-key: {{ .Values.bucket.key | b64enc }}
  aws-s3-key-secret: {{ .Values.bucket.secret | b64enc }}
{{- else if .Values.bucket.json }}
  gcs-key: {{ .Values.bucket.json }}
{{- end }}
{{- end -}}
