{{- range $key, $value := .Values.secrets }}
{{- if $value }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pg-database.fullname" $ }}-{{ $key }}-secret
  annotations:
    "helm.sh/hook": pre-install
  labels:
{{ include "pg-database.labels" $ | indent 4 }}
type: Opaque
stringData:
  password: {{ $value }}
  username: {{ $key }}
{{- end }}
{{- end }}
