kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployer-role-binding
  namespace: common
subjects:
- kind: User
  name: marthinus.kruger@4cgroup.co.za
- kind: User
  name: malvern.pontius@4cgroup.co.za
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deployer-role
