apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: vault-auth
  namespace: linkerd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: linkerd
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: vault-auth
  namespace: linkerd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator