kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: viewer-role-binding
  namespace: common
subjects:
- kind: User
  name: justin.schreuder@4cgroup.co.za
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: viewer-role
