kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: common
  name: viewer-role
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployments", "replicasets", "ingresses"]
  verbs: ["watch"]
- apiGroups: [""]
  resources: ["pods", "jobs", "services", "configmaps", "secrets", "pods/attach", "pods/exec"]
  verbs: ["watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["watch"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["watch"]
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["watch"]
- apiGroups: [""]
  resources: ["pods/log", "pods/status"]
  verbs: ["watch"]