bases:
- ../scale-3-5
patchesStrategicMerge:
- ./only-zoo-5.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: kafka
    namespace: kafka
  path: kafka-zookeeper-connect-only-zoo.json
