# Source: prometheus-mongodb-exporter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: data-mongodb
  name: mongodb-metrics
  labels:
    app.kubernetes.io/name: prometheus-mongodb-exporter
    app.kubernetes.io/instance: mongodb-metrics
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: prometheus-mongodb-exporter-2.8.1
    app: mongodb-service